Class {
	#name : #VB6PropertyGet,
	#superclass : #Object,
	#instVars : [
		'argsList',
		'statements',
		'args',
		'typesOfAssignedValues',
		'name',
		'propertyGetCalls',
		'visibility',
		'type',
		'variables',
		'constants',
		'ctx',
		'statementType',
		'scope',
		'program',
		'module',
		'isDeclaredAsArray',
		'scopedElements',
		'scopedElementsSymbolTable'
	],
	#category : #'VB6-ProleapMetaModel'
}
